fix: text for various cards
LegacyGwent/LegacyGwent pull request #362
Opened 2023-01-10 23:06 UTC by sharunkumar

2023-01-11 10:20 UTC, neal2018 requested changes

2023-01-11 10:20 UTC, neal2018 commented on src/Cynthia.Card.Unity/src/Cynthia.Unity.Card/Packages/packages-lock.json
> +        "com.unity.test-framework": "1.1.1"
Please do not modify this file

2023-01-11 21:05 UTC, sharunkumar commented on src/Cynthia.Card.Unity/src/Cynthia.Unity.Card/Packages/packages-lock.json
> +        "com.unity.test-framework": "1.1.1"
committed by mistake, reverted 👍

2023-01-12 06:45 UTC, neal2018 approved these changes
LGTM @DeusSeuca

2023-01-14 02:57 UTC, merged